import { AdminUser, StoredAdminUser } from '../types';
import { UserModel } from '../models/UserModel';

export class UserController {
  static async login(username: string, password: string): Promise<{ success: boolean; user?: AdminUser; error?: string }> {
    try {
      const user = UserModel.authenticateUser(username, password);

      if (!user) {
        return { success: false, error: 'Tên đăng nhập hoặc mật khẩu không đúng' };
      }

      UserModel.setCurrentSession(user);
      return { success: true, user };
    } catch (error) {
      console.error('Login error:', error);
      return { success: false, error: 'Có lỗi xảy ra khi đăng nhập' };
    }
  }

  static async logout(): Promise<void> {
    UserModel.clearCurrentSession();
  }

  static getCurrentUser(): AdminUser | null {
    return UserModel.getCurrentSession();
  }

  static async addUser(userData: { username: string; fullName: string; role: 'superadmin' | 'staff'; password: string }): Promise<{ success: boolean; error?: string }> {
    try {
      // Validate input
      if (!userData.username || !userData.fullName || !userData.password) {
        return { success: false, error: 'Vui lòng điền đầy đủ thông tin' };
      }

      // Check if username already exists
      const existingUsers = UserModel.getAllUsers();
      if (existingUsers.some(u => u.username === userData.username)) {
        return { success: false, error: 'Tên đăng nhập đã tồn tại' };
      }

      const newUser: StoredAdminUser = {
        id: '', // Will be generated by model
        username: userData.username,
        fullName: userData.fullName,
        role: userData.role,
        password: userData.password
      };

      UserModel.addUser(newUser);
      return { success: true };
    } catch (error) {
      console.error('Add user error:', error);
      return { success: false, error: 'Có lỗi xảy ra khi thêm tài khoản' };
    }
  }

  static async removeUser(userId: string): Promise<{ success: boolean; error?: string }> {
    try {
      const currentUser = this.getCurrentUser();
      if (!currentUser) {
        return { success: false, error: 'Bạn cần đăng nhập để thực hiện thao tác này' };
      }

      const userToRemove = UserModel.findUserById(userId);
      if (!userToRemove) {
        return { success: false, error: 'Không tìm thấy tài khoản cần xóa' };
      }

      if (userToRemove.id === currentUser.id) {
        return { success: false, error: 'Không thể xóa tài khoản hiện tại' };
      }

      UserModel.removeUser(userId);
      return { success: true };
    } catch (error) {
      console.error('Remove user error:', error);
      return { success: false, error: 'Có lỗi xảy ra khi xóa tài khoản' };
    }
  }

  static getAllUsers(): StoredAdminUser[] {
    return UserModel.getAllUsers();
  }

  static hasPermission(user: AdminUser | null, requiredRole: 'superadmin' | 'staff'): boolean {
    if (!user) return false;
    if (requiredRole === 'staff') return true; // Any logged in user
    return user.role === 'superadmin';
  }
}
